apiVersion: {{ include "deploymentversion" . }}
kind: Deployment
metadata:
  name: kube-apiserver
  namespace: {{ .Release.Namespace }}
  labels:
    garden.sapcloud.io/role: controlplane
    app: kubernetes
    role: apiserver
spec:
  minReadySeconds: 30
  revisionHistoryLimit: 0
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: kubernetes
      role: apiserver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        {{- if .Values.serviceAccountConfig }}
        {{- if .Values.serviceAccountConfig.signingKey}}
        checksum/service-account-signing-key: {{ include ( print $.Template.BasePath "/service-account-signing-key-secret.yaml") . | sha256sum }}
        {{- end }}
        {{- end }}
        checksum/configmap-audit-policy: {{ include (print $.Template.BasePath "/audit-policy.yaml") . | sha256sum }}
        checksum/secret-oidc-cabundle: {{ include (print $.Template.BasePath "/oidc-ca-secret.yaml") . | sha256sum }}
        checksum/configmap-blackbox-exporter: {{ include (print $.Template.BasePath "/blackbox-exporter-config.yaml") . | sha256sum }}
        checksum/configmap-admission-config: {{ include (print $.Template.BasePath "/admission-config.yaml") . | sha256sum }}
{{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
      labels:
        garden.sapcloud.io/role: controlplane
        app: kubernetes
        role: apiserver
        networking.gardener.cloud/to-dns: allowed
        networking.gardener.cloud/to-public-networks: allowed
        networking.gardener.cloud/to-private-networks: allowed
        networking.gardener.cloud/to-shoot-networks: allowed
        networking.gardener.cloud/from-prometheus: allowed
    spec:
      priorityClassName: gardener-shoot-controlplane
      tolerations:
      - effect: NoExecute
        operator: Exists
      initContainers:
      - name: set-iptable-rules
        image: {{ index .Values.images "alpine-iptables" }}
        command: ['/bin/sh', '-c', 'iptables -A INPUT -i tun0 -p icmp -j ACCEPT && iptables -A INPUT -i tun0 -m state --state NEW -j DROP']
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
      containers:
      - name: kube-apiserver
        image: {{ index .Values.images "hyperkube" }}
        imagePullPolicy: IfNotPresent
        command:
        - /usr/bin/hyperkube
        {{- if semverCompare "< 1.15" .Values.kubernetesVersion }}
        - apiserver
        {{- else }}
        - kube-apiserver
        {{- end }}
        - --enable-admission-plugins={{ include "kube-apiserver.admissionPlugins" . | trimSuffix "," }}
        - --admission-control-config-file={{ include "kube-apiserver.admissionPluginConfigFileDir" . }}/admission-configuration.yaml
        - --allow-privileged=true
        - --anonymous-auth=false
        - --audit-log-path=/var/lib/audit.log
        - --audit-policy-file=/etc/kubernetes/audit/audit-policy.yaml
        - --audit-log-maxsize=100
        - --audit-log-maxbackup=5
        - --authorization-mode=Node,RBAC
        {{- if .Values.enableBasicAuthentication }}
        - --basic-auth-file=/srv/kubernetes/auth/basic_auth.csv
        {{- end }}
        - --client-ca-file=/srv/kubernetes/ca/ca.crt
        - --enable-aggregator-routing=true
        - --enable-bootstrap-token-auth=true
        - --http2-max-streams-per-connection=1000
        - --etcd-cafile=/srv/kubernetes/etcd/ca/ca.crt
        - --etcd-certfile=/srv/kubernetes/etcd/client/tls.crt
        - --etcd-keyfile=/srv/kubernetes/etcd/client/tls.key
        - --etcd-servers=https://etcd-main-client:{{ .Values.etcdServicePort }}
        - --etcd-servers-overrides=/events#https://etcd-events-client:{{ .Values.etcdServicePort }}
        {{- if .Values.enableEtcdEncryption }}
        - --encryption-provider-config=/etc/kubernetes/etcd-encryption-secret/encryption-configuration.yaml
        {{- end }}
        {{- include "kube-apiserver.featureGates" . | trimSuffix "," | indent 8 }}
        - --kubelet-preferred-address-types=InternalIP,Hostname,ExternalIP
        - --kubelet-client-certificate=/srv/kubernetes/apiserver-kubelet/kube-apiserver-kubelet.crt
        - --kubelet-client-key=/srv/kubernetes/apiserver-kubelet/kube-apiserver-kubelet.key
        - --insecure-port=0
        {{- include "kube-apiserver.oidcConfig" . | indent 8 }}
        - --profiling=false
        - --proxy-client-cert-file=/srv/kubernetes/aggregator/kube-aggregator.crt
        - --proxy-client-key-file=/srv/kubernetes/aggregator/kube-aggregator.key
        - --requestheader-client-ca-file=/srv/kubernetes/ca-front-proxy/ca.crt
        - --requestheader-extra-headers-prefix=X-Remote-Extra-
        - --requestheader-group-headers=X-Remote-Group
        - --requestheader-username-headers=X-Remote-User
        {{- include "kube-apiserver.runtimeConfig" . | trimSuffix "," | indent 8 }}
        - --secure-port={{ required ".securePort is required" .Values.securePort }}
        - --service-cluster-ip-range={{ .Values.shootNetworks.service }}
        - --service-account-key-file=/srv/kubernetes/service-account-key/id_rsa
        - --token-auth-file=/srv/kubernetes/token/static_tokens.csv
        - --tls-cert-file=/srv/kubernetes/apiserver/kube-apiserver.crt
        - --tls-private-key-file=/srv/kubernetes/apiserver/kube-apiserver.key
        - --tls-cipher-suites={{ include "kubernetes.tlsCipherSuites" . | replace "\n" "," | trimPrefix "," }}
        {{- include "kube-apiserver.apiAudiences" . | indent 8 }}
        {{- include "kube-apiserver.serviceAccountConfig" . | indent 8 }}
        - --v=2
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - sleep 5
        livenessProbe:
          httpGet:
            scheme: HTTPS
            path: /healthz
            port: {{ required ".securePort is required" .Values.securePort }}
            httpHeaders:
            - name: Authorization
              value: Bearer {{ .Values.probeCredentials }}
          successThreshold: 1
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 15
        readinessProbe:
          httpGet:
            scheme: HTTPS
            path: /healthz
            port: {{ required ".securePort is required" .Values.securePort }}
            httpHeaders:
            - name: Authorization
              value: Bearer {{ .Values.probeCredentials }}
          successThreshold: 1
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 15
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        ports:
        - name: https
          containerPort: {{ required ".securePort is required" .Values.securePort }}
          protocol: TCP
        {{- if .Values.apiServerResources }}
        resources:
{{ toYaml .Values.apiServerResources | indent 10 }}
        {{- end }}
        volumeMounts:
        - name: audit-policy-config
          mountPath: /etc/kubernetes/audit
        - name: ca
          mountPath: /srv/kubernetes/ca
        - name: ca-etcd
          mountPath: /srv/kubernetes/etcd/ca
        - name: ca-front-proxy
          mountPath: /srv/kubernetes/ca-front-proxy
        - name: etcd-client-tls
          mountPath: /srv/kubernetes/etcd/client
        - name: kube-apiserver
          mountPath: /srv/kubernetes/apiserver
        - name: service-account-key
          mountPath: /srv/kubernetes/service-account-key
        {{- if .Values.enableBasicAuthentication }}
        - name: kube-apiserver-basic-auth
          mountPath: /srv/kubernetes/auth
        {{- end }}
        - name: static-token
          mountPath: /srv/kubernetes/token
        - name: kube-apiserver-kubelet
          mountPath: /srv/kubernetes/apiserver-kubelet
        - name: kube-aggregator
          mountPath: /srv/kubernetes/aggregator
        {{- if .Values.oidcConfig.caBundle }}
        - name: kube-apiserver-oidc-cabundle
          mountPath: /srv/kubernetes/oidc
        {{- end }}
        {{- if .Values.serviceAccountConfig }}
        {{- if .Values.serviceAccountConfig.signingKey }}
        - name: kube-apiserver-service-account-signing-key
          mountPath: /srv/kubernetes/service-account-signing-key
        {{- end }}
        {{- end }}
        - name: kube-apiserver-admission-config
          mountPath: {{ include "kube-apiserver.admissionPluginConfigFileDir" . }}
        - name: etcssl
          mountPath: /etc/ssl
          readOnly: true
        - name: ssl-certs-hosts
          mountPath: /usr/share/ca-certificates
          readOnly: true
        {{- if .Values.enableEtcdEncryption }}
        - name: etcd-encryption-secret
          mountPath: /etc/kubernetes/etcd-encryption-secret
          readOnly: true
        {{- end }}
      - name: vpn-seed
        image: {{ index .Values.images "vpn-seed" }}
        imagePullPolicy: IfNotPresent
        env:
        - name: MAIN_VPN_SEED
          value: "true"
        - name: OPENVPN_PORT
          value: "4314"
        - name: APISERVER_AUTH_MODE
          value: client-cert
        - name: APISERVER_AUTH_MODE_CLIENT_CERT_CA
          value: /srv/secrets/vpn-seed/ca.crt
        - name: APISERVER_AUTH_MODE_CLIENT_CERT_CRT
          value: /srv/secrets/vpn-seed/tls.crt
        - name: APISERVER_AUTH_MODE_CLIENT_CERT_KEY
          value: /srv/secrets/vpn-seed/tls.key
        - name: SERVICE_NETWORK
          value: {{ .Values.shootNetworks.service }}
        - name: POD_NETWORK
          value: {{ .Values.shootNetworks.pod }}
        - name: NODE_NETWORK
          value: {{ .Values.shootNetworks.node }}
        ports:
        - name: tcp-tunnel
          containerPort: 1194
          protocol: TCP
        resources:
          requests:
            cpu: 11m
            memory: 16Mi
          limits:
            cpu: 300m
            memory: 512Mi
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /srv/secrets/vpn-seed
          name: vpn-seed
        - mountPath: /srv/secrets/tlsauth
          name: vpn-seed-tlsauth
      - name: blackbox-exporter
        image: {{ index .Values.images "blackbox-exporter" }}
        args:
        - --config.file=/vpn/blackbox.yaml
        ports:
        # port name must be max 15 characters long
        - name: blackbox-export
          containerPort: {{ required ".blackboxExporterPort is required" .Values.blackboxExporterPort }}
          protocol: TCP
        resources:
          requests:
            cpu: 5m
            memory: 16Mi
          limits:
            cpu: 50m
            memory: 128Mi
        volumeMounts:
        - name: blackbox-exporter-config-apiserver
          mountPath: /vpn
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: audit-policy-config
        configMap:
          name: audit-policy-config
      - name: ca
        secret:
          secretName: ca
      - name: ca-etcd
        secret:
          secretName: ca-etcd
      - name: ca-front-proxy
        secret:
          secretName: ca-front-proxy
      - name: kube-apiserver
        secret:
          secretName: kube-apiserver
      - name: etcd-client-tls
        secret:
          secretName: etcd-client-tls
      - name: service-account-key
        secret:
          secretName: service-account-key
      {{- if .Values.enableBasicAuthentication }}
      - name: kube-apiserver-basic-auth
        secret:
          secretName: kube-apiserver-basic-auth
      {{- end }}
      - name: static-token
        secret:
          secretName: static-token
      - name: kube-apiserver-kubelet
        secret:
          secretName: kube-apiserver-kubelet
      - name: kube-aggregator
        secret:
          secretName: kube-aggregator
      {{- if .Values.oidcConfig.caBundle }}
      - name: kube-apiserver-oidc-cabundle
        secret:
          secretName: kube-apiserver-oidc-cabundle
      {{- end }}
      {{- if .Values.serviceAccountConfig }}
      {{- if .Values.serviceAccountConfig.signingKey }}
      - name: kube-apiserver-service-account-signing-key
        secret:
          secretName: kube-apiserver-service-account-signing-key
      {{- end }}
      {{- end }}
      - name: kube-apiserver-admission-config
        configMap:
          name: kube-apiserver-admission-config
      - name: vpn-seed
        secret:
          secretName: vpn-seed
      - name: vpn-seed-tlsauth
        secret:
          secretName: vpn-seed-tlsauth
      - name: etcssl
        hostPath:
          path: /etc/ssl
      - name: ssl-certs-hosts
        hostPath:
          path: /usr/share/ca-certificates
      - name: blackbox-exporter-config-apiserver
        configMap:
          name: blackbox-exporter-config-apiserver
      {{- if .Values.enableEtcdEncryption }}
      - name: etcd-encryption-secret
        secret:
          defaultMode: 420
          secretName: etcd-encryption-secret
      {{- end }}
